version: '3'

volumes:
  local_data: {}
  local_data_pgadmin: {}

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: prueba
      POSTGRES_PASSWORD: prueba
      POSTGRES_DB: EstVentas

    ports:
      - "5432:5432"
    volumes:
      - local_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    volumes:
      - local_data_pgadmin:/var/lib/pgadmin