version: '3'

volumes:
  local_data: {}
  local_data_pgadmin: {}

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database_name

    ports:
      - "5432:5432"
    volumes:
      - local_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: your_email@example.com
      PGADMIN_DEFAULT_PASSWORD: your_password
    ports:
      - "5050:80"
    volumes:
      - local_data_pgadmin:/var/lib/pgadmin